### ISSUE TITLE
Cannot assign type 'double' to 'Py_ssize_t'

### ISSUE THREAD

**Issue by yangzhao-666** [justinmaojones/starr#35]
Hi,

When I try to `pip install starr`, there's error occurred: `starr/src/_sumtree_array.pyx:49:12: Cannot assign type 'double' to 'Py_ssize_t'`. 

Any ideas on why this happened? Thank you very much!

**Comment by justinmaojones** [comment]
This should be fixed now in 0.3.2.  A `pip install starr==0.3.2` should do the trick.
